### ISSUE TITLE
UnboundLocalError: local variable 'interactive_flag' referenced before assignment

### ISSUE THREAD

**Issue by lanekelly** [summerstay/Infinite-Adventure#1]
Hello! Was trying it out on Colab. Making these two choices results in an UnboundLocalError:

Would you like to load a game? (Y or N) >>>n
Would you like to pregenerate room descriptions? It takes about an hour upfront, but gameplay is faster. (Y or N) >>> n

....(things happen)....

Traceback (most recent call last):
  File "./src/InfiniteAdventure.py", line 447, in <module>
    fire.Fire(interact_model)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./src/InfiniteAdventure.py", line 309, in interact_model
    if interactive_flag == 0:
UnboundLocalError: local variable 'interactive_flag' referenced before assignment

**Comment by summerstay** [comment]
I apologize, I was making changes yesterday and broke some things. Choosing n, n works now.
